spring:
  profiles:
    active: dev
  application:
    name: monitor-service-prometheus
# mybatis 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
management:
  endpoints:
    web:
      exposure:
        include: "*" # include表示需要暴露的endpoint，配置时使用“,”隔开，你也可以用*让所有endpoint暴露出来
    metrics:
      tags:
        application: ${spring.application.name}
#端口号配置
server:
  port: 8090
  servlet:
    context-path: /api

